Feature/mobile-menu-header
barteknr1/Projekt-grupowy pull request #10
Opened 2022-12-16 21:32 UTC by benbrzezinski

2022-12-16 22:27 UTC, barteknr1 requested changes

2022-12-16 22:27 UTC, barteknr1 commented on src/partials/header.html
> +      </button>
Pointer i działanie linku ma być na całym przycisku, nie tylko na tekście.

2022-12-16 22:27 UTC, barteknr1 commented on src/sass/components/_mobile-menu.scss
> +  filter: drop-shadow(-8px 0px 20px rgba(0, 0, 0, 0.25));
Fajna funkcja, niestety cały czas widoczna :)

2022-12-17 09:03 UTC, benbrzezinski commented on src/sass/components/_mobile-menu.scss
> +  filter: drop-shadow(-8px 0px 20px rgba(0, 0, 0, 0.25));
A dobre oko nie zauważyłem :)

2022-12-17 11:42 UTC, barteknr1 approved these changes

2022-12-17 11:43 UTC, merged