footer mobile added
barteknr1/Projekt-grupowy pull request #11
Opened 2022-12-16 21:36 UTC by DamianPiechota

2022-12-17 11:33 UTC, barteknr1 requested changes
Przede wszystkim trzeba poprawić nazwy klas i ich zagnieżdżenie w scss.
Zamień wszystkie line-height na mnożniki. Dzięki temu będą skalowalne.
Popraw pozycję znaczka telegramu.

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +    padding: 22px;
Container spycha wszystko do środka z prawej i lewej po 20px. Jak już będą wszystkie sekcje wtedy się ułoży odstępy pionowe. Póki co można zostawić padding-bottom: 43;

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +  &--top {
Zrób z tego element &__wrapper

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +    &_description {
&__description

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +    &_socials {
Zrób z tego samodzielny blok

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      padding-top: 50px;
Zamiast padding tutaj daj margin-bottom na slogan

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      padding-block: 43px;
Margin zamiast padding

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      font-family: 'DM Sans';
DM Sans jest w body, nie trzeba go nadpisywać

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      font-family: 'DM Sans';
DM Sans nie trzeba wpisywać

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +  &--bottom {
&__bottom

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +    align-items: center;
Nie ma wpływu na zawartość

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      font-style: normal;
Nie ma wpływu na zawartość

2022-12-17 11:33 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      font-size: 14px;
14px jest w body

2022-12-17 19:58 UTC, DamianPiechota commented
Please check the changes

2022-12-18 11:35 UTC, barteknr1 requested changes
Trzeba poprawić nazwy - te które omawialiśmy, zostawiłem podpowiedź. Reszty na razie OK :)

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      a {
W żadnym wypadku nie używamy tagów jako selektorów. <a> musi mieć klasę zgodną z BEM, w tym wypadku będzie to footer-right__address, bo footer-right jest osobnym blokiem

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +.socials {
Socialsy trzeba dać w oddzielnym pliku scss

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +  }
Dodać margin-bottom: 50px;

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +  /*padding-top: 50px;*/
margin-bottom: 46px;

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +        text-decoration: none;
text-decoration: none jest w resecie

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +    .copyright {
footer__copyright

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      color: #000000;
Czarny jest domyślnym kolorem, linijka niepotrzebna

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      font-weight: 400;
font-weight jest domyślną wartością - niepotrzebne. Wywal wszystkie 400 tylko się upewnij, że nie ma dziedziczenia innej wartości

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      font-style: normal;
normal jest dymyślną wartością, niepotrzebne

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      font-family: 'Titan One';
font-family: 'Titan One', cursive; - trzeba określać jeszcze typ czcionki, dzięki temu przy niezaczytaniu tej konkretnej przeglądarka wybierze inną tego samego typu. Później dodam zmienną na to

2022-12-18 11:35 UTC, barteknr1 commented on src/sass/components/_footer.scss
> +      flex-direction: row;
Dodaj padding-bottom: 91px; na tablet
Dodaj kolejne media na desktop: tam będzie dla bottom 97px

2022-12-18 15:53 UTC, DamianPiechota commented
Fixed errors reported by the leader

2022-12-18 21:33 UTC, barteknr1 approved these changes

2022-12-18 21:33 UTC, merged