Create modal-map
barteknr1/Projekt-grupowy pull request #30
Opened 2022-12-20 20:27 UTC by Ddemkowicz

2022-12-21 11:24 UTC, barteknr1 requested changes
Twoja mapka jest widoczna na samym końcu i nie pojawia się po kliknięciu w przycisk

2022-12-22 10:35 UTC, Grzybkowa commented on src/js/modal-map.js
> +/*(() => {
It seems that file is not relevant anymore. Can you please remove it?

2022-12-22 10:35 UTC, Grzybkowa commented on src/index.html
> +    <script src="./js/modal-map.js"></script>
As you're using open-modal.js, this one is not needed. Can you please remove this file as well? :)

2022-12-22 10:35 UTC, Grzybkowa commented on src/js/modal-map.js
> +  const refs = {
Commented classes are not needed anymore. Can you please remove them ?

2022-12-22 17:24 UTC, barteknr1 approved these changes

2022-12-22 17:25 UTC, merged